name: Codeflash Optimizations

on:
  pull_request:
    paths:
      - "src/backend/base/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  optimize:
    name: Optimize new Python code in this PR
    if: ${{ github.actor != 'codeflash-ai[bot]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
    env:
      CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
      CODEFLASH_PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Setup Environment"
        uses: ./.github/actions/setup-uv
      - name: Run Codeflash Optimizer
        run: uv run codeflash
      - name: Minimize uv cache
        run: uv cache prune --ci